version: '3'
services: 
  edp-api-proxy:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: 52north/deu-proxy:latest
    ports: 
      - 9090:9090
    environment: 
      - SEARCH_ENDPOINT=https://data.europa.eu/api/hub/search/search
      - WHITELIST_UPDATE_INTERVAL_MINUTES=60
      - WHITELIST_STORAGE_DIR=/var/lib/ckan-proxy/whitelist.json
      - LOGGING_LEVEL=trace
    volumes:
      - whitelist:/var/lib/ckan-proxy/

volumes: 
  whitelist: {}
