apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 52north

bases:
  - ../base

configMapGenerator:
  - name: config
    behavior: merge
    literals:
      - HOST_NAME=data.europa.eu
      - API_HOST_NAME=data.europa.eu

images:
  - name: 52north/deu-viewer:latest
    newTag: 1.0.2
  - name: 52north/deu-proxy:latest
    newTag: 2.0.2

