# Use a base image with Node.js 14.21.3
FROM node:14.21.3

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Copy the entire project to the working directory
COPY . .

# Install dependencies
RUN npm install

# Set Node.js and npm versions
RUN npm install -g npm@6.14.18

# Expose the port on which the application will run (change if needed)
EXPOSE 8080

# Set the command to start the application in development mode
CMD [ "npm", "run", "dev" ]
