PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dqv: <http://www.w3.org/ns/dqv#>

SELECT (COUNT(DISTINCT(?dist)) as ?count) ?value
{
    GRAPH ?g1
    {
        ?dist a dcat:Distribution
    }
    GRAPH ?g2
    {
        ?dist dqv:hasQualityMeasurement [
            dqv:isMeasurementOf <%1$s> ;
                dqv:value ?value
        ]
    }
} GROUP BY ?value
