apiVersion: v1
kind: Service
metadata:
  name: nc-permit-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nc-permit
  ports:
    - protocol: TCP
      port: 8102
      targetPort: 8102
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nc-permit
  namespace: {{ .Values.namespace }}
  labels:
    app: nc-permit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nc-permit
  template:
    metadata:
      labels:
        app: nc-permit
    spec:
      volumes:
      - name: nc-configmap
        configMap:
          name: nc-configmap
          items:
            - key: config.yml
              path: config.yml
      - name: sqlite-permit
        persistentVolumeClaim:
          claimName: sqlite-permit
      containers:
      - name: nc-permit
        image: code.europa.eu:4567/healthdataeu-nodes/hdeupoc/nc_datapermit:{{ .Values.releaseTag }}
        ports:
        - containerPort: 8102
        volumeMounts:
        - name: nc-configmap
          mountPath: /usr/src/app/config.yml
          subPath: config.yml
          readOnly: true
        - name: sqlite-permit
          mountPath: /usr/src/app/db/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-permit
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi