apiVersion: v1
kind: ConfigMap
metadata:
  name: nc-configmap
  namespace: {{ .Values.namespace }}
data:
  config.yml: |-
    domibus:
      username: {{ .Values.domibus.username }}
      url: {{ .Values.domibus.url }}
      port: {{ default 8080 .Values.domibus.port }}
      usehttps: {{ default true .Values.domibus.usehttps }}
      from: {{ .Values.domibus.from }}
      to: {{ .Values.domibus.to }}
    messagechecker:
      port: 8151
      url: nc-messagechecker-service.{{ .Values.namespace }}.svc.cluster.local
    datapermit:
      port: 8102
      url: nc-permit-service.{{ .Values.namespace }}.svc.cluster.local
    gateway:
      port: 8100
---
apiVersion: v1
kind: Secret
metadata:
  name: passwords
  namespace: {{ .Values.namespace }}
stringData:
  .domibuspass: |-
{{ .Values.domibuspass | indent 4 }}