apiVersion: v1
kind: Service
metadata:
  name: nc-gateway-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nc-gateway
  type: NodePort  
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
      nodePort: {{ .Values.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: nc-gateway
  labels:
    app: nc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nc-gateway
  template:
    metadata:
      labels:
        app: nc-gateway
    spec:
      volumes:
      - name: nc-config
        configMap:
          name: nc-configmap
          items:
            - key: config.yml
              path: config.yml
      - name: nc-pass
        secret:
          secretName: passwords
          items:
            - key: .domibuspass
              path: .domibuspass
      containers:
      - name: nc-gateway
        image: code.europa.eu:4567/healthdataeu-nodes/hdeupoc/nc_gateway:{{ .Values.releaseTag }}
        ports:
        - containerPort: 8100
        volumeMounts:
        - name: nc-config
          mountPath: /usr/src/app/config.yml
          subPath: config.yml
          readOnly: true
        - name: nc-pass
          mountPath: /root/.domibuspass
          subPath: .domibuspass
          readOnly: true