apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 52north

bases:
  - ../base

configMapGenerator:
  - name: config
    behavior: merge
    literals:
      - HOST_NAME=ppe.data.europa.eu
      - API_HOST_NAME=ppe.data.europa.eu

images:
  - name: 52north/deu-viewer:latest
    newTag: 0.9.9
  - name: 52north/deu-proxy:latest