openapi: 3.0.3
info:
  version: ${project.version}
  title: Validation service for RDF based on SHACL
  x-logo:
    url: images/logo

servers:
  - url: ''

paths:
  /validation/report:
    post:
      description: Create and returns a shacl report for a given dcat-ap graph
      summary: SHACL based validation and report creation
      operationId: validationReport
      parameters:
        - name: shapeModel
          in: query
          description: "Shacl shapes for dcatap version to use"
          required: false
          schema:
            type: string
            enum:
              - "dcatap211level1"
              - "dcatap211level2"
              - "dcatap211level3"
              - "dcatap211"
              - "dcatap210level1"
              - "dcatap210"
              - "dcatap201"
              - "dcatap200"
              - "dcatap121"
              - "dcatap121orig"
              - "dcatap12"
              - "dcatap11"
              - "dcatap11orig"
              - "dcatapde102"
            default: "dcatap211"
      requestBody:
        description: The content to validate
        required: true
        content:
          application/rdf+xml:
            schema:
              type: string
          application/ld+json:
            schema:
              type: object
          application/n-triples:
            schema:
              type: string
          application/trig:
            schema:
              type: string
          text/turtle:
            schema:
              type: string
          text/n3:
            schema:
              type: string
      responses:
        '200':
          description: Successfully validated the input and created a report.
          content:
            text/turtle:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/ld+json:
              schema:
                type: object
            application/n-triples:
              schema:
                type: string
            application/trig:
              schema:
                type: string
            text/n3:
              schema:
                type: string
        '400':
          description: Bad request
