#
# Docker compose project used to startup the test environment.
#
# Usage:
#     Start:    docker-compose up -d | docker-compose -f docker-compose.yml up --build -d
#     Shutdown: docker-compose down
#     Logs:     docker-compose logs
#
# Configuration:
#   This file represents the architecture of the Domibus single node setup with MySQL

version: '3.9'
networks:
  domibus-mysql-nw:
    name: domibus-mysql-network
    
  public-nw:
    external: true
    
  hub-repo-nw:
    external: true
    
  central-nw:
    name: central-network
               
services:
  #
  # Domibus Tomcat MySQL Configuration
  #
  # Optional: can provide your own external database
  mysql:
    container_name: central-mysql
    image: code.europa.eu:4567/edelivery/docker/domibus-mysql8:5.0.4
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    security_opt:
      - seccomp:unconfined
    volumes:
      - shared_db_file_system:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      domibus-mysql-nw: {}

  central-domibus:
    container_name: central-domibus
    image: code.europa.eu:4567/edelivery/docker/domibus-tomcat9:5.0.4
    environment:
      - DB_TYPE=MySQL
      - DB_HOST=central-mysql
      - DB_PORT=3306
      - DB_USER=edelivery
      - DB_PASS=edelivery
      - LOGGER_LEVEL_ORG_APACHE_CXF=INFO
      - CHECK_DEFAULT_PASSWD=false
      - domibus.metrics.sl4j.reporter.enable=false
      - domibus.metrics.monitor.jms.queues=false
      - domibus.metrics.monitor.memory=false
      - domibus.metrics.monitor.gc=false
      - domibus.metrics.monitor.cached.threads=false
    ports:
      - "5080:8080"
    volumes:
      - ./domibus_central:/data/tomcat/conf/domibus
    depends_on:
      - mysql
    networks:
      domibus-mysql-nw: {}
      public-nw: {}
      central-nw: {}  
      
  centralservice-datadiscovery:
    container_name: centralservice-datadiscovery
    #image: code.europa.eu:4567/healthdataeu-nodes/hdeupoc/cs_datadiscovery:b0.3
    #build: ../hdeupoc/services/datadiscoverycentralservice/
    build: ../hdeupoc/services/datadiscoverycentralservice/
    mem_limit: 350m
    volumes:
      - ${PWD}/config.yml:/usr/src/app/config.yml
      - ${PWD}/.domibuspass:/root/.domibuspass
      - ${PWD}/.fairdatapointpass:/root/.fairdatapointpass
      - ${PWD}/ap_catalog.json:/usr/src/app/ap_catalog.json
    networks:
      central-nw: {}
      hub-repo-nw: {}

  centralservice-datapermit:
    container_name: centralservice-datapermit
    #image: code.europa.eu:4567/healthdataeu-nodes/hdeupoc/cs_datapermit:b0.3
    #build: ../hdeupoc/services/datapermitcentralservice
    build: ../hdeupoc/services/datapermitcentralservice/
    mem_limit: 350m
    ports:
      - "8103:8103"
    volumes:
      - ${PWD}/config.yml:/usr/src/app/config.yml
      - ${PWD}/.domibuspass:/root/.domibuspass
      - ${PWD}/ap_catalog.json:/usr/src/app/ap_catalog.json
    networks:
      central-nw: {}

  centralservice-messagechecker:
    container_name: centralservice-messagechecker
    #image: code.europa.eu:4567/healthdataeu-nodes/hdeupoc/cs_messagechecker:b0.3
    build: ../hdeupoc/services/messagechecker/
    mem_limit: 350m
    volumes:
      - ${PWD}/config.yml:/usr/src/app/config.yml
      - ${PWD}/.domibuspass:/root/.domibuspass
    networks:
      central-nw: {}
  

volumes:
  shared_db_file_system:
